version: 2.4

volumes:
  ignition-data:

services:
  ignition:
    build: .
    restart: always
    privileged: true
    ports:
      - 8088:8088
      - 8043:8043
    volumes:
      - ignition-data:/opt/ignition/data
    labels:
      io.balena.features.kernel-modules: 1
      io.balena.features.sysfs: 1
